### ISSUE TITLE
dual does not symmetrize

### ISSUE THREAD

**Issue by kalmarek** [JuliaOpt/SCS.jl#150]
```julia
m = JuMP.Model()
@variables m begin
    a
    b
    c
    λ
end
P = [a b; b c]
@constraint m sdp P in PSDCone();
@constraint m y₀ a + λ == 1;
@constraint m y₁ 2b == 1
@constraint m y₂ c == 1
@objective m Max λ 

# it's the minimization problem of x² + x + 1 

with_SCS = with_optimizer(SCS.Optimizer, eps=1e-10, verbose=true)
optimize!(m, with_SCS)
```

 * `value.(P)` returns `[0.25 0.5; 0.5 1.0]` (as expected)
 * `value.([m[:a], m[:b], m[:c], m[:λ]])` is about `[ 0.25,  0.50, 1.0, 0.75]` (as expected)
 * `dual.([m[:y₀], m[:y₁], m[:y₂]])` is about `[-1.0,  0.5, -0.25]` seems to have signs flipped
 * `dual.(m[:sdp])` is `[1.0 -1.0; 0.0 0.25]` which has one obvious(?) problem: it's not symmetric; I believe also that the off diagonal entry should be `-0.5` (so the signs here are correct)

@blegat could you please have a look?
cc: @tweisser, @vmagron

**Comment by blegat** [comment]
You should do `@constraint(m, sdp, Symmetric(P) in PSDCone())` with `using LinearAlgebra` to create a symmetric matrix. Otherwise, the cone use is the the cone of symmetric PSD matrices. See the comment at the top of this file:
https://github.com/JuliaOpt/MathOptInterface.jl/blob/2c0e0fc1c3fa096ebbe73c8fc61c045222751ffe/src/Bridges/Constraint/square.jl
If you don't use `Symmetric`, the dual is "the cone of matrices A such that A+Aᵀ" is symmetric and PSD.

**Comment by kalmarek** [comment]
thanks!
